# Analysis of experiment #4: Randomness of the pricing heuristic

## Read data

In [5]:
# Read csv

import pandas as pd

df = pd.read_csv("stats4.csv")

df

,instance,solver,run,nvertices,nedges,n,m,nvars,ncons,state,...,otherNodesNColsHeur,otherNodesNColsMwis1,otherNodesNColsMwis2,otherNodesNColsExact,otherNodesTime,otherNodesTimePool,otherNodesTimeHeur,otherNodesTimeMwis1,otherNodesTimeMwis2,otherNodesTimeExact
0,r_n130_p0.25_nA26_nB13_i1,byp_a0.3,0,130,2181,26,13,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,r_n170_p0.75_nA34_nB17_i2,byp_a0.3,0,170,10813,34,17,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,r_n170_p0.75_nA34_nB17_i0,byp_a0.3,0,170,10814,34,17,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,r_n170_p0.75_nA17_nB34_i4,byp_a0.3,0,170,10756,17,34,-1,-1,OPTIMAL,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,r_n150_p0.5_nA15_nB30_i4,byp_a0.3,0,150,5679,15,30,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,r_n170_p0.75_nA34_nB17_i3,byp_a0.1,0,170,10775,34,17,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
185,r_n170_p0.75_nA17_nB17_i3,byp_a0.1,0,170,10751,17,17,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
186,r_n150_p0.5_nA15_nB30_i0,byp_a0.1,0,150,5548,15,30,-1,-1,OPTIMAL,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
187,r_n150_p0.5_nA15_nB15_i2,byp_a0.1,0,150,5568,15,15,-1,-1,OPTIMAL,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
188,r_n150_p0.5_nA30_nB15_i3,byp_a0.1,0,150,5675,30,15,-1,-1,FEASIBLE,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df.columns

Index(['instance', 'solver', 'run', 'nvertices', 'nedges', 'n', 'm', 'nvars',
       'ncons', 'state', 'time', 'nodes', 'nodesLeft', 'lb', 'ub', 'gap',
       'ninfeas', 'ninfeasPrepro', 'ninfeasCheck', 'ninfeasAux', 'nint',
       'ngcp', 'gcpTime', 'nsol', 'nsolHeur', 'nsolLR', 'ntrivial', 'rootlb',
       'rootub', 'rootHeurTime', 'rootFeasTime', 'rootNCalls',
       'rootNCallsPool', 'rootNCallsHeur', 'rootNCallsMwis1',
       'rootNCallsMwis2', 'rootNCallsExact', 'rootNCols', 'rootNColsPool',
       'rootNColsHeur', 'rootNColsMwis1', 'rootNColsMwis2', 'rootNColsExact',
       'rootTime', 'rootTimePool', 'rootTimeHeur', 'rootTimeMwis1',
       'rootTimeMwis2', 'rootTimeExact', 'otherNodesHeurTime',
       'otherNodesFeasNCalls', 'otherNodesFeasTime', 'otherNodesNCalls',
       'otherNodesNCallsPool', 'otherNodesNCallsHeur', 'otherNodesNCallsMwis1',
       'otherNodesNCallsMwis2', 'otherNodesNCallsExact', 'otherNodesNCols',
       'otherNodesNColsPool', 'otherNodesNColsHeur', 'otherNodesNColsMwis1',
       'otherNodesNColsMwis2', 'otherNodesNColsExact', 'otherNodesTime',
       'otherNodesTimePool', 'otherNodesTimeHeur', 'otherNodesTimeMwis1',
       'otherNodesTimeMwis2', 'otherNodesTimeExact'],
      dtype='str')

## Summary

In [10]:
df3 = df.groupby(["solver"]).agg(
    {
        "state": [("feasible", lambda x: (x == "FEASIBLE").sum()), ("optimal", lambda x: (x == "OPTIMAL").sum())],
        "time": [("avg", "mean")],
        "rootNCallsHeur": [("avg", "mean")],
        "rootNColsHeur": [("avg", "mean")],
        "rootNCallsExact": [("avg", "mean")],
    }
).reset_index()
df3

     solver    state                time rootNCallsHeur rootNColsHeur  \
            feasible optimal         avg            avg           avg
0  byp_a0.0       41       7  516.546500    1326.875000    603.645833
1  byp_a0.1       40       7  531.223979    1234.042553    386.723404
2  byp_a0.2       40       7  511.056340    1192.978723    332.659574
3  byp_a0.3       40       7  508.343851    1185.531915    296.914894

  rootNCallsExact
              avg
0       44.708333
1       41.170213
2       37.914894
3       37.808511