# Analysis of experiment #1: DPCP heuristics

## Read data

In [2]:
# Read csv

import pandas as pd

df = pd.read_csv("stats1.csv")

# Some renames to improve readability
df["solver"] = df["solver"].str.replace("v2", "deg")
df["solver"] = df["solver"].str.replace("v3", "edg")

# For the unsolved instances,
# --> write NaN in ub
# --> write NaN in bestTime
# --> write NaN in bestIter
df.loc[df.state != "FEASIBLE", "value"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestTime"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestIter"] = float("nan")

# Rename some columns
df = df.rename(columns={'state': 'solved'})

df

,instance,solver,run,nvertices,nedges,n,m,solved,value,totalTime,totalIters,bestTime,bestIter
0,r_n170_p0.75_nA17_nB34_i1,heur_semigreedy2s_deg_a0.35,0,170,10781,17,34,FEASIBLE,4.0,24.03390,17000,3.815830,2796.0
1,r_n170_p0.75_nA17_nB17_i1,heur_semigreedy2s_deg_a0.35,0,170,10787,17,17,FEASIBLE,5.0,17.73560,17000,0.378629,364.0
2,r_n130_p0.25_nA26_nB26_i1,heur_semigreedy2s_deg_a0.35,0,130,2071,26,26,FEASIBLE,3.0,6.05510,13000,0.080036,166.0
3,r_n150_p0.5_nA15_nB30_i2,heur_semigreedy2s_deg_a0.35,0,150,5529,15,30,FEASIBLE,3.0,12.55130,15000,0.009836,7.0
4,r_n150_p0.5_nA15_nB15_i4,heur_semigreedy2s_deg_a0.35,0,150,5682,15,15,FEASIBLE,3.0,10.13610,15000,0.024533,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,r_n130_p0.25_nA26_nB26_i2,heur_semigreedy2s_edg_a0.4,0,130,2100,26,26,FEASIBLE,3.0,4.74152,13000,0.044299,105.0
696,r_n170_p0.75_nA34_nB17_i1,heur_semigreedy2s_edg_a0.4,0,170,10786,34,17,FEASIBLE,12.0,11.14100,17000,0.118372,170.0
697,r_n150_p0.5_nA30_nB30_i0,heur_semigreedy2s_edg_a0.4,0,150,5548,30,30,FEASIBLE,6.0,14.06210,15000,0.221153,234.0
698,r_n150_p0.5_nA30_nB15_i1,heur_semigreedy2s_edg_a0.4,0,150,5541,30,15,FEASIBLE,7.0,10.80270,15000,0.163890,224.0
699,r_n130_p0.25_nA26_nB13_i1,heur_semigreedy2s_edg_a0.4,0,130,2181,26,13,FEASIBLE,3.0,4.14814,13000,0.086924,265.0

## Summary

In [3]:
df2 = df.groupby(["solver"]).agg(
    {
        "solved": [("count", lambda x: (x == "FEASIBLE").sum())],
        "value": [("sum", "sum")],
        "totalTime": [("avg", "mean")],
        "bestIter": [("avg","mean"),("max", "max")]
    }
).reset_index()
df2

                         solver solved  value  totalTime bestIter
                                 count    sum        avg      avg      max
0    heur_semigreedy2s_deg_a0.1     50  276.0  14.800116  1129.72  14779.0
1   heur_semigreedy2s_deg_a0.15     50  274.0  14.799598  1867.82  14782.0
2    heur_semigreedy2s_deg_a0.2     50  278.0  14.839246  1114.40  13516.0
3   heur_semigreedy2s_deg_a0.25     50  279.0  14.831699   910.54   7157.0
4    heur_semigreedy2s_deg_a0.3     50  278.0  14.837391   914.08  11462.0
5   heur_semigreedy2s_deg_a0.35     50  275.0  14.834320  1666.76  13730.0
6    heur_semigreedy2s_deg_a0.4     50  275.0  14.896035  2001.12  13532.0
7    heur_semigreedy2s_edg_a0.1     50  274.0  11.749061  1349.20  11243.0
8   heur_semigreedy2s_edg_a0.15     50  277.0  11.712907  1112.58  13643.0
9    heur_semigreedy2s_edg_a0.2     50  277.0  11.726599   902.54  13583.0
10  heur_semigreedy2s_edg_a0.25     50  278.0  11.761514   871.60  16204.0
11   heur_semigreedy2s_edg_a0.3     50  276.0  11.723442  1424.54  16197.0
12  heur_semigreedy2s_edg_a0.35     50  280.0  11.731419   578.86  10775.0
13   heur_semigreedy2s_edg_a0.4     50  280.0  11.722517  1292.48  16013.0