# Analysis of experiment #2
## Number of repetitions of semigreedy heuristic

## Read data

In [2]:
# Read csv

import pandas as pd

df = pd.read_csv("stats2.csv")

# Some renames to improve readability
df["solver"] = df["solver"].str.replace("v2", "deg")
df["solver"] = df["solver"].str.replace("v3", "edg")

# For the unsolved instances,
# --> write NaN in ub, bestTime, bestIter
df.loc[df.state != "FEASIBLE", "value"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestTime"] = float("nan")
df.loc[df.state != "FEASIBLE", "bestIter"] = float("nan")

# Rename some columns
df = df.rename(columns={'state': 'solved'})

# Separate a column for the variant and the repetitions
df["variant"] = df.solver.apply(lambda s: s.split("_")[2])
df["repetitions"] = df.solver.apply(lambda s: int(s.split("_")[3][1:]))

df

,instance,solver,run,nvertices,nedges,n,m,solved,value,totalTime,totalIters,bestTime,bestIter,variant,repetitions
0,r_n170_p0.75_nA17_nB34_i1,heur_semigreedy2s_deg_r100,0,170,10781,17,34,FEASIBLE,4.0,23.64000,17000,2.352930,1747.0,deg,100
1,r_n170_p0.75_nA17_nB17_i1,heur_semigreedy2s_deg_r100,0,170,10787,17,17,FEASIBLE,5.0,17.57150,17000,0.263474,257.0,deg,100
2,r_n130_p0.25_nA26_nB26_i1,heur_semigreedy2s_deg_r100,0,130,2071,26,26,FEASIBLE,3.0,6.01743,13000,0.000793,0.0,deg,100
3,r_n150_p0.5_nA15_nB30_i2,heur_semigreedy2s_deg_r100,0,150,5529,15,30,FEASIBLE,3.0,12.33560,15000,0.006501,4.0,deg,100
4,r_n150_p0.5_nA15_nB15_i4,heur_semigreedy2s_deg_r100,0,150,5682,15,15,FEASIBLE,3.0,10.11440,15000,0.001720,1.0,deg,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,r_n130_p0.25_nA26_nB26_i2,heur_semigreedy2s_edg_r500,0,130,2100,26,26,FEASIBLE,3.0,23.60360,65000,0.002562,6.0,edg,500
496,r_n170_p0.75_nA34_nB17_i1,heur_semigreedy2s_edg_r500,0,170,10786,34,17,FEASIBLE,12.0,55.37090,85000,0.024586,24.0,edg,500
497,r_n150_p0.5_nA30_nB30_i0,heur_semigreedy2s_edg_r500,0,150,5548,30,30,FEASIBLE,6.0,71.19990,75000,0.541236,585.0,edg,500
498,r_n150_p0.5_nA30_nB15_i1,heur_semigreedy2s_edg_r500,0,150,5541,30,15,FEASIBLE,7.0,54.21850,75000,0.110530,148.0,edg,500
499,r_n130_p0.25_nA26_nB13_i1,heur_semigreedy2s_edg_r500,0,130,2181,26,13,FEASIBLE,3.0,21.00590,65000,0.060744,188.0,edg,500

## Summary

In [3]:
df2 = df.groupby(["solver", "variant", "repetitions"]).agg(
    {
        "solved": [("count", lambda x: (x == "FEASIBLE").sum())],
        "value": [("sum", "sum")],
        "totalTime": [("avg", "mean")],
        "bestIter": [("avg","mean"),("max", "max")]
    }
).reset_index()
df2 = df2.sort_values(["variant","repetitions"])
df2

                        solver variant repetitions solved  value   totalTime  \
                                                    count    sum         avg
0    heur_semigreedy2s_deg_r10     deg          10     50  285.0    1.448740
3    heur_semigreedy2s_deg_r50     deg          50     50  277.0    7.317976
1   heur_semigreedy2s_deg_r100     deg         100     50  276.0   14.784196
4   heur_semigreedy2s_deg_r500     deg         500     50  273.0   75.516810
2  heur_semigreedy2s_deg_r1000     deg        1000     50  267.0  152.267826
5    heur_semigreedy2s_edg_r10     edg          10     50  284.0    1.158216
8    heur_semigreedy2s_edg_r50     edg          50     50  278.0    5.813705
6   heur_semigreedy2s_edg_r100     edg         100     50  274.0   11.689659
9   heur_semigreedy2s_edg_r500     edg         500     50  270.0   59.101402
7  heur_semigreedy2s_edg_r1000     edg        1000     50  269.0  118.683376

   bestIter
        avg       max
0    109.28    1535.0
3    834.20    7368.0
1   1129.72   14779.0
4   3840.68   83101.0
2  17345.04  141395.0
5    106.72    1219.0
8    613.30    6752.0
6   1349.20   11243.0
9   4728.34   61683.0
7   6600.88   93770.0